repos:
  - repo: local
    hooks:
      - id: black
        name: checking black
        entry: black
        types: [python]
        stages: [commit]
        language: system
      - id: flake8
        name: checking flake8
        entry: flake8
        types: [python]
        stages: [commit]
        language: system
        args: [--max-line-length=120]
